apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: #{K8S_NAMESPACE}#
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://#{RDS_ENDPOINT}#:5432/#{DB_NAME}#
  APP_CORS_ALLOWED_ORIGINS: https://#{AMPLIFY_DOMAIN}#
  AWS_SECRET_NAME: #{SECRETS_MANAGER_KEY}#
  AWS_REGION: #{AWS_REGION}#
  PROJECT_NAME: #{PROJECT_NAME}#
  REDIS_HOST: redis
