apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: #{K8S_NAMESPACE}#
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://#{RDS_ENDPOINT}#:5432/#{DB_NAME}#
  APP_CORS_ALLOWED_ORIGINS: https://#{AMPLIFY_DOMAIN}#
  APP_PUBLIC_URL: https://#{CF_DOMAIN}#
  AWS_SECRET_NAME: #{SECRETS_MANAGER_KEY}#
  AWS_REGION: #{AWS_REGION}#
  APP_REDIS_HOST: redis
  APP_REDIS_PORT: "6379"
  COGNITO_ISSUER_URI: https://cognito-idp.#{AWS_REGION}#.amazonaws.com/#{COGNITO_USER_POOL_ID}#
