apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: todo-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: todo-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_USERNAME
      remoteRef:
        key: todo-dev/backend-secrets
        property: APP_USERNAME
    - secretKey: APP_PASSWORD
      remoteRef:
        key: todo-dev/backend-secrets
        property: APP_PASSWORD
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: todo-dev/backend-secrets
        property: SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: todo-dev/backend-secrets
        property: SPRING_DATASOURCE_PASSWORD
