apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: #{PROJECT_NAME}#-ingress
  namespace: #{K8S_NAMESPACE}#
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: #{BACKEND_TLS_CERTIFICATE_ARN}#
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/wafv2-acl-arn: #{WAF_ACL_ARN}#
    external-dns.alpha.kubernetes.io/hostname: #{BACKEND_API_DOMAIN}#
spec:
  ingressClassName: alb
  rules:
    - host: #{BACKEND_API_DOMAIN}#
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: #{PROJECT_NAME}#-service
                port:
                  number: 80
