services:
  aws-kubectl:
    build:
      context: .
      dockerfile: Dockerfile.aws-kubectl
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    ports:
      - "5005:5005"
    volumes:
      - ..:/workspace
      - kube-config:/root/.kube

  terraform:
    build:
      context: .
      dockerfile: Dockerfile.terraform
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    volumes:
      - ../infra:/infra

volumes:
  kube-config:
