services:
  aws-kubectl:
    build:
      context: .
      dockerfile: Dockerfile.aws-kubectl
    env_file: .env
    ports:
      - "5005:5005"
    volumes:
      - ..:/workspace
      - kube-config:/root/.kube

  terraform-backend:
    build:
      context: .
      dockerfile: Dockerfile.terraform-backend
    env_file: .env
    environment:
      TF_VAR_project_name: todo
      TF_VAR_aws_region: us-east-1
      TF_VAR_environment: dev
      TF_VAR_ssm_param_prefix: infra
    volumes:
      - ../infra-backend:/infra-backend

  maven:
    image: maven:3.9.8-eclipse-temurin-17
    working_dir: /workspace/backend
    volumes:
      - ..:/workspace
      - maven-repo:/root/.m2

volumes:
  kube-config:
  maven-repo:
