server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: ${PROJECT_NAME:todo}-backend
  config:
    import: optional:aws-secretsmanager:${AWS_SECRET_NAME}
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/todo}
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: false

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
