spring:
  config:
    import: ""
  cloud:
    aws:
      secretsmanager:
        enabled: false
  datasource:
    username: todo
    password: todo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""

app:
  local-auth:
    username: localuser
