name: Deploy Infrastructure

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"
      - ".github/workflows/deploy-infra.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    env:
      TF_VAR_project_name: ${{ vars.TF_VAR_PROJECT_NAME }}
      TF_VAR_github_repository: ${{ vars.TF_VAR_GITHUB_REPOSITORY }}
      TF_VAR_environment: ${{ vars.TF_VAR_ENVIRONMENT }}
      TF_VAR_ssm_param_prefix: ${{ vars.SSM_PARAM_PREFIX }}
      TF_VAR_db_username: ${{ vars.TF_VAR_DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_app_username: ${{ vars.TF_VAR_APP_USERNAME }}
      TF_VAR_app_password: ${{ secrets.TF_VAR_APP_PASSWORD }}
      TF_VAR_frontend_branch: ${{ vars.AMPLIFY_BRANCH_NAME }}
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_k8s_namespace: ${{ vars.TF_VAR_K8S_NAMESPACE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
